name: Dockerize Autoshop Flask Applications
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: python:3.8-slim-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, Tag, and Push Docker Images
        run: |
          for dir in PortalService OrderManagement NotificationGateway ProductManagement; do
            cd "$dir" || exit
            docker build -t "$dir" .
            docker push shawnpitts/"$dir"
            cd ..
          done