name: Dockerize Autoshop Flask Applications
on: 
  push:
    branches: [ main ]
jobs:
  build-container:
    name: Build Docker container image
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and deploy PortalService docker image
        working-directory: ./PortalService
        run: |
          docker build -t portal .
          docker push shawnpitts/portal:latest