name: Dockerize Autoshop Flask Applications
on: 
  push:
    branches: [ main ]
jobs:
  build-container:
    name: Build Docker container image
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, Tag, and Push Docker Images
        run: |
          for dir in "PortalService" "OrderManagement" "NotificationGateway" "ProductManagement";
          do
              # Check if the directory exists
              if [ "$dir" == "ProductService" ]; then
                  echo "Building and Pushing image for $dir"
                  docker build -t portal .
                  docker push shawnpitts/portal:latest
              elif [ "$dir" == "ProductService" ]; then
                  echo "Building and Pushing image for $dir"
                  docker build -t product .
                  docker push shawnpitts/product:latest
              elif [ "$dir" == "OrderManagement" ]; then
                  echo "Building and Pushing image for $dir"
                  docker build -t order .
                  docker push shawnpitts/order:latest
              elif [ "$dir" == "NotificationGateway" ]; then
                  echo "Building image for $dir"
                  docker build -t notify .
                  docker push shawnpitts/notify:latest
              fi
              cd ..
          done