name: Dockerize Autoshop Flask Applications
on: 
  push:
    branches: [ main ]
jobs:
  build-container:
    name: Build Docker container image
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and deploy PortalService docker image
        working-directory: ./PortalService
        run: |
          docker build -t portal .
          docker push shawnpitts/portal:latest

      - name: Build and deploy ProductManagement docker image
        working-directory: ./ProductManagement
        run: |
          docker build -t product .
          docker push shawnpitts/product:latest

      - name: Build and deploy OrderManagement docker image
        working-directory: ./OrderManagement
        run: |
          docker build -t order .
          docker push shawnpitts/order:latest
      
      - name: Build and deploy NotificationGateway docker image
        working-directory: ./NotificationGateway
        run: |
          docker build -t notification .
          docker push shawnpitts/notification:latest                              