name: Dockerize Autoshop Flask Applications
on: 
  push:
    branches: [ main ]
jobs:
  build-container:
    name: Build Docker container image
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push PortalService Docker Image
        working-directory: ./PortalService
        run: |
          docker build -t portal .
          docker tag portal shawnpitts/portal
          docker push shawnpitts/portal:latest

      - name: Push ProductManagement Docker Image
        working-directory: ./ProductManagement
        run: |
          docker build -t product .
          docker tag product shawnpitts/product
          docker push shawnpitts/product:latest

      - name: Push OrderManagement Docker Image
        working-directory: ./OrderManagement
        run: |
          docker build -t orders .
          docker tag orders shawnpitts/orders
          docker push shawnpitts/orders:latest
      
      - name: Push NotificationGateway Docker Image
        working-directory: ./NotificationGateway
        run: |
          docker build -t notification .
          docker tag notification shawnpitts/notification
          docker push shawnpitts/notification:latest                              